- main.go
- metrics/metrics.go
- muxer/interfaces.go
- muxer/interfaces_test.go
Captures packets on all interfaces.
Fixes #8
Part of m-lab/dev-tracker#442 and m-lab/dev-tracker#443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/12)
> Capture and mux packets on all interfaces.

- saver/tcp.go
- saver/tcp_test.go
A unit test was wrong, which meant that the output was never actually checked to be correct. Which meant it was not correct.
Fixes #17 
Part of m-lab/dev-tracker#442 and m-lab/dev-tracker#443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/16)
> Fix packet truncation

- main.go
- saver/tcp.go
- saver/tcp_test.go
Fixes #18
Fixes #20 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/21)
> Fix logs, memory usage, header size

- tcpinfohandler/handler.go
- tcpinfohandler/handler_test.go
After https://github.com/m-lab/tcp-info/pull/111 this change updates the handler implementation to satisfiy the new `eventsocket.Handler` interface by adding a `context.Context` parameter to the Open and Close methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/22)
> Add context to Open & Close methods

- saver/tcp.go
- saver/tcp_test.go
Allow the garbage collector to collect garbage by using more narrowly
scoped variables inside functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/23)
> Allow garbage to be garbage.

- demuxer/tcp_test.go
- saver/tcp.go
- saver/tcp_test.go
Trades CPU for RAM and disk IO.  Both RAM and (especially) disk IO are scarce resources on server machines, so this is probably a good trade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/24)
> Save to .pcap.gz instead of .pcap

- saver/tcp.go
Addresses https://github.com/m-lab/packet-headers/issues/20
This change will return immediately if there is no UUID to identify the flow, causing all buffered and new packets to be discarded immediately. As well, this change reduces the static packet channel buffer from 833,333 to 8192. During load testing with an adhoc metric, I never observed the chan utilization above 8k and we have a metric counting "missed" packets so if this is a problem, we'll know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/25)
> Default return after uuid miss, and reduce chan buffer

- demuxer/tcp.go
- demuxer/tcp_test.go
- main.go
- main_test.go
- saver/tcp.go
- saver/tcp_test.go
This change alters the savePackets logic by splitting the read/save loop into two parts:
* Buffer for up to 5 seconds (UUIDDelay), then look for the UUID
* If the UUID is not found, return immediately
* If the UUID is found, continue the read/save loop for the full `duration`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/26)
> Abandon savers without UUIDs after 5 seconds

- .travis.yml
- main.go
- main_test.go
- muxer/interfaces.go
- muxer/interfaces_test.go
Should prevent the host context from being forwarded many many packets that it does not care about.
Part of #20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/27)
> Add a BPF filter and turn off promiscuous mode

- saver/tcp.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/29)
> Log flow id with filename

- demuxer/flowkey.go
- main.go
- main_test.go
- saver/tcp.go
- tcpinfohandler/handler.go
Also, convert the `-eventsocket` flag to the one provided in `tcpinfo.eventsocket`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/30)
> Ensure all IPv4 addresses use only 4 bytes.

- demuxer/flowkey.go
- demuxer/flowkey_test.go
- demuxer/tcp.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/31)
> Anonymize logs

- saver/tcp.go
- saver/tcp_test.go
Currently the saver state appears to stall at "uuidwait" even though uuid handling occurs immediately. This change adds a new state for "readingpackets-withuuid".
My only reservation is that the new state name is kind of long. Suggestions welcome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/32)
> Add a new state after uuidwait and before dircreation

- demuxer/tcp.go
- demuxer/tcp_test.go
- main.go
- saver/export_test.go
- saver/tcp.go
- saver/tcp_test.go
Puts streaming (or not streaming) under control of a command-line flag.  This should allow us to easily test which configuration works best.  Once we have decided which works best in practice, we should make that option the default and then remove the flag.
(Please do not review until #35 is merged, at which point I will rebase this PR on master)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/37)
> Add flag for streaming.

- demuxer/tcp.go
- demuxer/tcp_test.go
- main.go
As part of the GC cycle, try and give RAM back to the OS.  Should execute every ~30 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/36)
> Explicitly try and hand RAM back to the OS

- saver/tcp.go
Also, the use of contexts has been cleaned up and clarified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/41)
> The read-UUID loop is now guaranteed to execute at least once

- .travis.yml
- Dockerfile
- demuxer/tcp.go
- demuxer/tcp_test.go
- main.go
- metrics/metrics.go
This change adds a new flag (`-maxheap`) to packet-headers that limits the total RAM used by the process. This change requires a new feature of go1.19 [`debug.SetMemoryLimit`][1].
From local testing, in response to a SYN flood event:
* `SetMemoryLimit` alone is not sufficient to prevent eventual RAM exhaustion. New savers are created faster than the timeout and GC removes them.
* Conditional creation of `saver.StartNew` alone is not sufficient to prevent RAM exhaustion either because the GC does not activate frequently enough.
Shorter settings for `-uuidwaittimeout` (down to 100ms) had no effect on the eventual RAM exhaustion.
When total RAM used is greater than `maxHeap`, new streams will be ignored. In effect, this both limits new memory allocations and may prevent some legitimate …
> Flag -maxheap

- main.go
Pusher used to handled creating data directories if they didn't already exist. We removed that functionality from Pusher because it seems more appropriate for the producer of a datatype to create its own data directory. However, we found that pcap did not do this. This commit should cause pcap to create its own data directory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/50)
> Create data dir if it doesn't exist

- Dockerfile
This allows the pod to run as a non-root user with no additional special capabilities.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/51)
> Sets cap_net_raw capability on packet-headers binary

- main.go
This change adds a filter so that the interfaces used are actually administratively "up". This is necessary because packets cannot be collected from down interfaces. For example:
```
iterfaces.go:100: Could not create libpcap client for {'\x02' 'ל' "eno1" "3c:ec:ef:ce:f7:8e" "broadcast|multicast"} (error: eno1: That device is not up)
```
Part of:
* https://github.com/m-lab/ops-tracker/issues/1798
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/52)
> Filter interfaces that are up

- main.go
This change adds a filter so that the interfaces used are actually administratively "up". This is necessary because packets cannot be collected from down interfaces. For example:
```
iterfaces.go:100: Could not create libpcap client for {'\x02' 'ל' "eno1" "3c:ec:ef:ce:f7:8e" "broadcast|multicast"} (error: eno1: That device is not up)
```
Part of:
* https://github.com/m-lab/ops-tracker/issues/1798
The previous change from https://github.com/m-lab/packet-headers/pull/52 only filtered down interfaces that were provided with the `-interfaces` flag, which neglected all automatically detected interfaces.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/packet-headers/53)
> Select only interfaces that are "up"
